DROP TABLE IF EXISTS DoctorAvailability;
DROP TABLE IF EXISTS Notification;
DROP TABLE IF EXISTS Consultation;
DROP TABLE IF EXISTS Appointment;
DROP TABLE IF EXISTS Doctor;
DROP TABLE IF EXISTS Patient;
DROP TABLE IF EXISTS User;
