CREATE TABLE IF NOT EXISTS User (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    birthDate DATE NOT NULL,
    cpf VARCHAR(20) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role ENUM('PATIENT', 'DOCTOR') NOT NULL
);

CREATE TABLE IF NOT EXISTS Patient (
    userId BIGINT PRIMARY KEY,
    healthPlan VARCHAR(255),
    CONSTRAINT fk_patient_user FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Doctor (
    userId BIGINT PRIMARY KEY,
    specialty VARCHAR(100) NOT NULL,
    CONSTRAINT fk_doctor_user FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Appointment (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    doctorId BIGINT NOT NULL,
    patientId BIGINT NOT NULL,
    startDateTime DATETIME NOT NULL,
    endDateTime DATETIME NOT NULL,
    status ENUM('PENDING', 'CONFIRMED', 'REJECTED', 'ADVANCED', 'DELAYED', 'CANCELLED') NOT NULL DEFAULT 'PENDING',
    notes TEXT,
    createdBy BIGINT NOT NULL,
    editedBy BIGINT,
    lastUpdate TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_appointment_doctor FOREIGN KEY (doctorId) REFERENCES Doctor(userId),
    CONSTRAINT fk_appointment_patient FOREIGN KEY (patientId) REFERENCES Patient(userId),
    CONSTRAINT fk_appointment_createdBy FOREIGN KEY (createdBy) REFERENCES User(id),
    CONSTRAINT fk_appointment_editedBy FOREIGN KEY (editedBy) REFERENCES User(id)
);

CREATE TABLE IF NOT EXISTS Consultation (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    appointmentId BIGINT NOT NULL,
    startDateTime DATETIME NOT NULL,
    endDateTime DATETIME NOT NULL,
    status ENUM('SCHEDULED', 'IN_PROGRESS', 'FINISHED', 'CANCELLED') NOT NULL,
    medicalNotes TEXT,
    CONSTRAINT fk_consultation_appointment FOREIGN KEY (appointmentId) REFERENCES Appointment(id)
);

CREATE TABLE IF NOT EXISTS Notification (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    userId BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    dateTime DATETIME NOT NULL,
    readFlag BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_notification_user FOREIGN KEY (userId) REFERENCES User(id)
);

CREATE TABLE IF NOT EXISTS doctoravailability (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    doctorId BIGINT NOT NULL,
    weekday ENUM('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY') NOT NULL,
    startTime TIME NOT NULL,
    endTime TIME NOT NULL,
    CONSTRAINT fk_doctor_availability FOREIGN KEY (doctorId) REFERENCES Doctor(userId)
);
